version: '3'

networks:
  ideashop:

services:
  postgres-server:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${ADMIN_JWT_SECRET}
    volumes:
      - ./.data:/var/lib/postgresql/data/
    networks:
      - ideashop
    restart: always

  strapi-server:
    depends_on:
      - postgres-server
    image: ideamall/ideashop-server
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_URL=postgres://postgres:${ADMIN_JWT_SECRET}@postgres-server:5432/postgres
      - NODE_ENV=production
    volumes:
      - ./config/sync:/app/config/sync
    networks:
      - ideashop
    ports:
      - 1337:1337
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:1337/ || exit 1']
      interval: 3s
      retries: 5
      start_period: 30s
    labels:
      - autoheal=true
    restart: always

  autoheal:
    image: willfarrell/autoheal:1.2.0
    networks:
      - ideashop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  caddy:
    depends_on:
      - strapi-server
    image: caddy
    networks:
      - ideashop
    ports:
      - 80:80
      - 443:443
    command: caddy reverse-proxy --from your.domain.com --to strapi-server:1337
